version: '3'

services:
  nginx:
    container_name: teste-nginx
    image: nginx
    ports:
      - '8080:80'
    links:
      - phpfpm
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx

  phpfpm:
    container_name: teste-php
    build:
      context: .
      dockerfile: ./docker/phpfpm.docker
    image: dev/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
